=== Starting Health Checker ===
Monitoring http://wisecow.local every 5s, expecting 200
2025-09-21T00:37:02.159683 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E286A50>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:09.860229 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E24F390>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:17.254049 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E24FD90>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:24.851751 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E25EFD0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:32.685713 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E25E8B0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:41.093195 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E3017F0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:48.498113 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2F9E10>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:37:55.890829 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FA580>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:03.211349 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FA7A0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:10.519195 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FA9C0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:17.819426 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FABE0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:25.283458 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FAE00>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:32.650634 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB020>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:39.969961 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB240>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:47.355972 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB460>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:38:54.739743 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB680>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:02.248373 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB8A0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:09.584610 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FBAC0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:16.924457 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FBAC0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:24.368281 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB8A0>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:31.697853 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB680>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:39.084103 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB460>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
2025-09-21T00:39:46.807885 - http://wisecow.local - DOWN - error: HTTPConnectionPool(host='wisecow.local', port=80): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x000001801E2FB240>: Failed to resolve 'wisecow.local' ([Errno 11001] getaddrinfo failed)"))
